name: ourphone.tf
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on ourphone.tf
      uses: appleboy/ssh-action@master
      with:
        host: ourphone.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_ourphone/
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/ourphone.tf/https:\/\/ourphone.tf/g" config.toml
          ./build.sh
